version: '3'

services:
    app:
        container_name: DockerNode
        build: '.'
        ports: 
            - '4000:4000'
        links:
            - mongo
    mongo:
        image: mongo:3.0.4
        ports: 
            - "27017:27017"
        